services:
  lovely-forensic-suite:
    container_name: lfs_container
    hostname: lfs
    restart: always
    build:
      context: .
      args:
          - PASSWORD=root
    ports:
      - "13000:5000"
      - "13022:22"
      
    # OPSI KRUSIAL:
    # Diperlukan agar perintah 'mount' di dalam fitur analisis disk image dapat berfungsi.
    privileged: true