services:
  jj:
    container_name: jj_container
    hostname: jj
    restart: always
    build:
      context: .
      args:
          - PASSWORD=root
    ports:
      - "12000:8080"
      - "12022:22"
    environment:
      - FLAG=RTR{fake_flag}
