version: '3.1'

services:
  # --- poke ---
  poke:
    container_name: poke_container
    hostname: poke
    restart: always
    build:
      context: poke
      args:
        - PASSWORD=$PASSWORD_10000
    volumes:
      - ../receiver/flags/poke.txt:/flag.txt:ro
      - ../utils/bashrc:/root/.bashrc:ro
      - ../utils/preexec.sh:/root/.preexec.sh:ro
    ports:
      - "10000:80"
      - "10022:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  c2:
    restart: always
    container_name: c2_container
    hostname: c2
    build:
      context: c2
      args:
        - PASSWORD=$PASSWORD_11000
    ports:
      - "11000:8000"    
      - "11022:22"      
    volumes:
      - ../receiver/flags/c2.txt:/flag.txt:ro
      - ../utils/bashrc:/root/.bashrc:ro
      - ../utils/preexec.sh:/root/.preexec.sh:ro
    environment:
      - TERM=xterm-256color
    security_opt:
      - seccomp:unconfined
    extra_hosts:
      - "host.docker.internal:host-gateway"

  lovely-forensic-suite:
    container_name: lfs_container
    hostname: lfs
    restart: always
    build:
      context: .
      args:
          - PASSWORD=$PASSWORD_13000
    ports:
      - "13000:5000"
      - "13022:22"
    volumes:
      - ../receiver/flags/lfs.txt:/flag.txt:ro
      - ../utils/bashrc:/root/.bashrc:ro
      - ../utils/preexec.sh:/root/.preexec.sh:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true