
services:
  c2:
    restart: always
    container_name: c2_container
    hostname: c2
    build:
      context: c2
      args:
        - PASSWORD=$PASSWORD_11000
    ports:
      - "11000:8000"    
      - "11022:22"      
    volumes:
      - ../receiver/flags/c2.txt:/flag.txt:ro
      - ../utils/bashrc:/root/.bashrc:ro
      - ../utils/preexec.sh:/root/.preexec.sh:ro
    environment:
      - TERM=xterm-256color
    security_opt:
      - seccomp:unconfined
    extra_hosts:
      - "host.docker.internal:host-gateway"

  notes:
    container_name: notes_container
    hostname: notes
    restart: always
    ports:
      - "12000:8000"
      - "12022:22"
    build:
      context: Notes
      args:
          - PASSWORD=$PASSWORD_12000
    volumes:
      - ../receiver/flags/notes.txt:/flag.txt:ro
      - ../utils/bashrc:/root/.bashrc:ro
      - ../utils/preexec.sh:/root/.preexec.sh:ro
    environment:
      - FLAG=RTRTNI25{PLACEHOLDER}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  lovely-forensic-suite:
    container_name: lfs_container
    hostname: lfs
    restart: always
    build:
      context: lfs
      args:
          - PASSWORD=$PASSWORD_13000
    ports:
      - "13000:5000"
      - "13022:22"
    volumes:
      - ../receiver/flags/lfs.txt:/flag.txt:ro
      - ../utils/bashrc:/root/.bashrc:ro
      - ../utils/preexec.sh:/root/.preexec.sh:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true

  lunachef:
    build:
      context: LunaChef
      dockerfile: Dockerfile
      args:
          - PASSWORD=$PASSWORD_14000
    container_name: lunachef_container
    hostname: lunachef
    ports:
      - "14000:5000"
      - "14022:22"
    volumes:
      - ../receiver/flags/lunachef.txt:/flag.txt:ro
      - ../utils/bashrc:/root/.bashrc:ro
      - ../utils/preexec.sh:/root/.preexec.sh:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"