version: "3"

services:
  c2:
    restart: always
    container_name: c2_container
    hostname: c2
    build:
      context: ./
      args:
        - PASSWORD=root
    ports:
      - "11000:8000"    
      - "11022:22"      
    volumes:
      - ./flag.txt:/flag.txt:ro
    environment:
      - TERM=xterm-256color
    security_opt:
      - seccomp:unconfined
