version: "3"

services:
  c2:
    restart: always
    container_name: c2-system
    build:
      context: ./
      args:
        - PASSWORD=TNI_C2_PASSWORD_15000
    ports:
      - "15000:8000"    
      - "15022:22"      
    volumes:
      - ./flag.txt:/flag.txt:ro
    environment:
      - TERM=xterm-256color
    security_opt:
      - seccomp:unconfined
